### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by OfficialAudite** [laytan/odin-mysql#4]
![image](https://github.com/laytan/odin-mysql/assets/10171579/3d4e205d-86b6-4b85-9ced-c5598ca45f1b)

![image](https://github.com/laytan/odin-mysql/assets/10171579/394f7057-4a01-432b-bf35-b9ee09224f97)

OS: **Windows**

**Comment by laytan** [comment]
Yes, you have to install the mysql library first, this repository just has the bindings
